### ISSUE TITLE
Send print jobs on a USB laser printer

### ISSUE THREAD

**Issue by drskullster** [LgHS/asciimaton#5]
We should be able to print on a USB laser printer. We can use CUPS, there's a Python binding called pycups that we should test.

**Comment by drskullster** [comment]
CUPS is set up and working on the Pi.

**Comment by iooner** [comment]
`print subprocess.Popen("lpr -P NOM_IMPRIMANTE /path/path/fessestoprint.jpg", shell=True, stdout=subprocess.PIPE).stdout.read()`

Cups : `lpr -P NOM_IMPRIMANTE /path/path/fessestoprint.jpg`

**Comment by iooner** [comment]
Doc for LPR cups : https://www.cups.org/doc/options.html
